version: '3.8'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_bataval
    image: image_bataval
    restart: always
    ports:
      - "5580:80"
      - "5582:5582"
